# EnchantmentSlots by @PQguanfang
#
# READ THE WIKI: enchantmentslots.superiormc.cn

# Settings
settings:
  debug: true
  auto-add-slots-limit: true
  default-slots: 1
  trigger:
    EnchantItemEvent:
      enabled: true
    InventoryClickEvent:
      enabled: true

# Messages
messages:
  add-lore: "&7Enchantment Slots: %amount%"
  plugin-reloaded: "&#98FB98[EnchantmentSlots] &fPlugin reloaded!"
  help-main: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
  help-main-admin: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
  help-main-console: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
  slots-limit-reached: "§x§9§8§F§B§9§8[EnchantmentSlots] §cYour item has reached its enchantment limits!"
  error-args: "&#98FB98[EnchantmentSlots] &cWrong command usage, if you need help, use /mythictotem help!"
  error-miss-permission: "&#98FB98[EnchantmentSlots] &cYou don't have permission to use this command!"