# EnchantmentSlots by @PQguanfang
#
# READ THE WIKI: simple.superiormc.cn/

# Settings
settings:
  debug: false
  add-lore:
    # Does not support other packed-based item, enchants plugins.
    # Like EcoEnchants, EcoItems.
    # They will always put their lore at first location and EnchantmentSlots can do anything about it.
    at-first-or-last: false
    display-value: "&#ff3300Enchantment Slots: %amount%"
    # One word without color code only.
    check-value: "Slots"
    trigger:
      Packet:
        enabled: false
        auto-check: false
        whitelist-items:
          - wooden_pickaxe
          - stone_pickaxe
          - iron_pickaxe
          - golden_pickaxe
          - diamond_pickaxe
          - netherite_pickaxe
          - wooden_hoe
          - stone_hoe
          - iron_hoe
          - golden_hoe
          - diamond_hoe
          - netherite_hoe
          - wooden_axe
          - stone_axe
          - iron_axe
          - golden_axe
          - diamond_axe
          - wooden_shovel
          - stone_shovel
          - iron_shovel
          - golden_shovel
          - diamond_shovel
          - netherite_shovel
          - wooden_sword
          - stone_sword
          - iron_sword
          - golden_sword
          - diamond_sword
          - netherite_sword
          - fishing_rod
          - elytra
          - bow
          - crossbow
          - carrot_on_a_stick
          - shield
          - turtle_helmet
          - leather_helmet
          - chainmail_helmet
          - iron_helmet
          - golden_helmet
          - diamond_helmet
          - netherite_helmet
          - leather_chestplate
          - chainmail_chestplate
          - iron_chestplate
          - golden_chestplate
          - diamond_chestplate
          - netherite_chestplate
          - leather_leggings
          - chainmail_leggings
          - iron_leggings
          - golden_leggings
          - diamond_leggings
          - netherite_leggings
          - leather_boots
          - chainmail_boots
          - iron_boots
          - golden_boots
          - diamond_boots
          - netherite_boots
      EnchantItemEvent:
        enabled: true
      InventoryClickEvent:
        enabled: true
    black-creative-mode: false
  default-slots:
    default: 5
    vip: 10
  # Only work for extra slot items.
  # Remove this section if you don't want this feature.
  max-slots:
    default: 10
    vip: 15
  slots-conditions:
    vip:
      - 'permission: group.vip'
  close-inventory-if-reached-limit: true
  remove-illegal-extra-enchant: true
  black-creative-mode-player: true

add-slot-items:
  A:
    material: PAPER
    name: '&dExtra Enchantment Slot &7(+1)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 1
  B:
    material: PAPER
    custom-model-data: 5
    name: '&dExtra Enchantment Slot &7(+5)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 5

# Messages
messages:
  plugin-reloaded: "&#98FB98[EnchantmentSlots] &fPlugin reloaded!"
  help-main: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
  help-main-admin: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
    &f/es setslots <amount> &7- Set enchantment slot to specified amount.
    &f/es giveslots <amount> &7- Add enchantment slots specified amount.
    &f/es giveslots <itemID> <player> &7- Give extra slot item to specified player.
  help-main-console: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
    &f/es giveslots <itemID> <player> &7- Give extra slot item to specified player.
  give-extra-slot-item: "&#98FB98[EnchantmentSlots] &aGave %player% extra slot item %item% x%amount%"
  success-add: "&#98FB98[EnchantmentSlots] &aAdd %amount% extra main hand item enchantment slot!"
  success-set: "&#98FB98[EnchantmentSlots] &aSet main hand item enchantment slot to %amount%!"
  slots-limit-reached: "&#98FB98[EnchantmentSlots] &cYour item has reached its enchantment limits!"
  max-slots-reached: "&#98FB98[EnchantmentSlots] &cYour item can not have more enchantment slots!"
  error-args: "&#98FB98[EnchantmentSlots] &cWrong command usage, if you need help, use /es help!"
  error-miss-permission: "&#98FB98[EnchantmentSlots] &cYou don't have permission to use this command!"
  error-in-game: "&#98FB98[EnchantmentSlots] &cYou have to use this command in game!"
  error-no-item: "&#98FB98[EnchantmentSlots] &cCan not get item in your main hand!"
  player-not-found: "&#98FB98[EnchantmentSlots] &cWe can't find player %player%!"