# EnchantmentSlots by @PQguanfang
#
# READ THE WIKI: enchantmentslots.superiormc.cn

# Settings
settings:
  debug: false
  auto-add-slots-limit: true
  default-slots: 5
  close-inventory-if-reached-limit: true
  trigger:
    EnchantItemEvent:
      enabled: true
    InventoryClickEvent:
      enabled: true


add-slot-items:
  A:
    material: PAPER
    name: '&dExtra Enchantment Slot &7(+1)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 1
  B:
    material: PAPER
    name: '&dExtra Enchantment Slot &7(+5)'
    lore:
      - '&fDrag this item into your item to use!'
    add-slots: 5

# Messages
messages:
  add-lore: "&#ff3300Enchantment Slots: %amount%"
  plugin-reloaded: "&#98FB98[EnchantmentSlots] &fPlugin reloaded!"
  help-main: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
  help-main-admin: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
    &f/es setslots &7- Set mainhand enchantment slots.
  help-main-console: |
    &#98FB98&lEnchantmentSlots &7Made by @PQguanfang
    &f/es help &7- View help.
    &f/es reload &7- Reload the plugin.
  success-add: "§x§9§8§F§B§9§8[EnchantmentSlots] §aAdd %amount% extra main hand item enchantment slot!"
  success-set: "§x§9§8§F§B§9§8[EnchantmentSlots] §aSet main hand item enchantment slot to %amount%!"
  slots-limit-reached: "§x§9§8§F§B§9§8[EnchantmentSlots] §cYour item has reached its enchantment limits!"
  error-args: "&#98FB98[EnchantmentSlots] &cWrong command usage, if you need help, use /mythictotem help!"
  error-miss-permission: "&#98FB98[EnchantmentSlots] &cYou don't have permission to use this command!"
  error-in-game: "&#98FB98[EnchantmentSlots] &cYou have to use this command in game!"
  error-no-item: "&#98FB98[EnchantmentSlots] &cCan not get item in your main hand!"
  player-not-found: "&#98FB98[EnchantmentSlots] &cWe can't find player %player%!"